version: '3.8'

services:
  web:
    build: .
    container_name: cybrscan_web
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-cybrscan-docker-secret-key-change-in-production}
      - FLASK_ENV=production
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@cybrscan.local}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes:
      - ./database:/app/database
      - ./client_databases:/app/client_databases
      - ./static/uploads:/app/static/uploads
      - ./static/deployments:/app/static/deployments
      - ./generated_scanners:/app/generated_scanners
      - ./configs:/app/configs
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - cybrscan_network

  nginx:
    image: nginx:alpine
    container_name: cybrscan_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/app/static:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - cybrscan_network

  certbot:
    image: certbot/certbot
    container_name: cybrscan_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - cybrscan_network

networks:
  cybrscan_network:
    driver: bridge